# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .bytes import *
from .id import *
from .integer import *
from .password import *
from .pet import *
from .provider import *
from .shuffle import *
from .string import *
from .uuid import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "random",
  "mod": "index/bytes",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/bytes:Bytes": "Bytes"
  }
 },
 {
  "pkg": "random",
  "mod": "index/id",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/id:Id": "Id"
  }
 },
 {
  "pkg": "random",
  "mod": "index/integer",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/integer:Integer": "Integer"
  }
 },
 {
  "pkg": "random",
  "mod": "index/password",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/password:Password": "Password"
  }
 },
 {
  "pkg": "random",
  "mod": "index/pet",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/pet:Pet": "Pet"
  }
 },
 {
  "pkg": "random",
  "mod": "index/shuffle",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/shuffle:Shuffle": "Shuffle"
  }
 },
 {
  "pkg": "random",
  "mod": "index/string",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/string:String": "String"
  }
 },
 {
  "pkg": "random",
  "mod": "index/uuid",
  "fqn": "pulumi_random",
  "classes": {
   "random:index/uuid:Uuid": "Uuid"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "random",
  "token": "pulumi:providers:random",
  "fqn": "pulumi_random",
  "class": "Provider"
 }
]
"""
)
