# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['PetArgs', 'Pet']

@pulumi.input_type
class PetArgs:
    def __init__(__self__, *,
                 keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 separator: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Pet resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] keepers: Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        :param pulumi.Input[_builtins.float] length: The length (in words) of the pet name. Defaults to 2
        :param pulumi.Input[_builtins.str] prefix: A string to prefix the name with.
        :param pulumi.Input[_builtins.str] separator: The character to separate words in the pet name. Defaults to "-"
        """
        if keepers is not None:
            pulumi.set(__self__, "keepers", keepers)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if separator is not None:
            pulumi.set(__self__, "separator", separator)

    @_builtins.property
    @pulumi.getter
    def keepers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        """
        return pulumi.get(self, "keepers")

    @keepers.setter
    def keepers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "keepers", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The length (in words) of the pet name. Defaults to 2
        """
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A string to prefix the name with.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter
    def separator(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The character to separate words in the pet name. Defaults to "-"
        """
        return pulumi.get(self, "separator")

    @separator.setter
    def separator(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "separator", value)


@pulumi.input_type
class _PetState:
    def __init__(__self__, *,
                 keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 separator: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Pet resources.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] keepers: Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        :param pulumi.Input[_builtins.float] length: The length (in words) of the pet name. Defaults to 2
        :param pulumi.Input[_builtins.str] prefix: A string to prefix the name with.
        :param pulumi.Input[_builtins.str] separator: The character to separate words in the pet name. Defaults to "-"
        """
        if keepers is not None:
            pulumi.set(__self__, "keepers", keepers)
        if length is not None:
            pulumi.set(__self__, "length", length)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if separator is not None:
            pulumi.set(__self__, "separator", separator)

    @_builtins.property
    @pulumi.getter
    def keepers(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        """
        return pulumi.get(self, "keepers")

    @keepers.setter
    def keepers(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "keepers", value)

    @_builtins.property
    @pulumi.getter
    def length(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        The length (in words) of the pet name. Defaults to 2
        """
        return pulumi.get(self, "length")

    @length.setter
    def length(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "length", value)

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A string to prefix the name with.
        """
        return pulumi.get(self, "prefix")

    @prefix.setter
    def prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "prefix", value)

    @_builtins.property
    @pulumi.getter
    def separator(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The character to separate words in the pet name. Defaults to "-"
        """
        return pulumi.get(self, "separator")

    @separator.setter
    def separator(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "separator", value)


@pulumi.type_token("random:index/pet:Pet")
class Pet(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 separator: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Pet resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] keepers: Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        :param pulumi.Input[_builtins.float] length: The length (in words) of the pet name. Defaults to 2
        :param pulumi.Input[_builtins.str] prefix: A string to prefix the name with.
        :param pulumi.Input[_builtins.str] separator: The character to separate words in the pet name. Defaults to "-"
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[PetArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Pet resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PetArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PetArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 length: Optional[pulumi.Input[_builtins.float]] = None,
                 prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 separator: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PetArgs.__new__(PetArgs)

            __props__.__dict__["keepers"] = keepers
            __props__.__dict__["length"] = length
            __props__.__dict__["prefix"] = prefix
            __props__.__dict__["separator"] = separator
        super(Pet, __self__).__init__(
            'random:index/pet:Pet',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            keepers: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            length: Optional[pulumi.Input[_builtins.float]] = None,
            prefix: Optional[pulumi.Input[_builtins.str]] = None,
            separator: Optional[pulumi.Input[_builtins.str]] = None) -> 'Pet':
        """
        Get an existing Pet resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] keepers: Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        :param pulumi.Input[_builtins.float] length: The length (in words) of the pet name. Defaults to 2
        :param pulumi.Input[_builtins.str] prefix: A string to prefix the name with.
        :param pulumi.Input[_builtins.str] separator: The character to separate words in the pet name. Defaults to "-"
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PetState.__new__(_PetState)

        __props__.__dict__["keepers"] = keepers
        __props__.__dict__["length"] = length
        __props__.__dict__["prefix"] = prefix
        __props__.__dict__["separator"] = separator
        return Pet(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def keepers(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
        """
        return pulumi.get(self, "keepers")

    @_builtins.property
    @pulumi.getter
    def length(self) -> pulumi.Output[_builtins.float]:
        """
        The length (in words) of the pet name. Defaults to 2
        """
        return pulumi.get(self, "length")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A string to prefix the name with.
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def separator(self) -> pulumi.Output[_builtins.str]:
        """
        The character to separate words in the pet name. Defaults to "-"
        """
        return pulumi.get(self, "separator")

